#!/bin/bash

cd $HOME/gnome/source

for i in *; do
  if [ -d $i ]; then
    cd $i;
    if test -d .git; then
      git stash
      echo " " $i; git pull
      git stash pop
    fi
    cd ..
  fi
done
jhbuild build gnome-shell
